### ISSUE TITLE
Formatting Options

### ISSUE THREAD

**Issue by prstn** [e7h4n/alfred-workflow-moment#1]
It is possible I am just missing something, but...

It would be nice if a user could pass in a formatting string, something like: 

**moment format ddd, hA** 
_Sun, 3PM_

[Here's a link to the related moment docs](http://momentjs.com/docs/#/displaying/format/)

Thanks for the super useful workflow, btw!

**Comment by e7h4n** [comment]
I'll do this.

**Comment by e7h4n** [comment]
@prstn done, please download the latest release.

![screen shot 2016-02-24 at 7 56 27 pm](https://cloud.githubusercontent.com/assets/813596/13284691/cfacba62-db30-11e5-81c7-c7eec966e66b.png)

**Comment by prstn** [comment]
Nice!
