### ISSUE TITLE
Set Timezone / Offset

### ISSUE THREAD

**Issue by mnkhouri** [e7h4n/alfred-workflow-moment#2]
I work with UTC time a lot. It would be useful to be able to either:

Always show the UTC time in the results, e.g:

```
moment 1234234442000
1234234442000
7 years ago
2009-02-09 21:54:02 -05:00
2009-02-10 02:54:02 +00:00
```

OR

Be able to set timezone/offset, like `moment 1234234442000 set offset 0` or `moment 1234234442000 set timezone UTC`

Thanks for the workflow, it's great!

**Comment by e7h4n** [comment]
It's reasonable, I'll make it.

**Comment by e7h4n** [comment]
`moment set tz 0` is supported by 1.2.4

**Comment by mnkhouri** [comment]
Thank you!
